### ISSUE TITLE
Add Blog template

### ISSUE THREAD

**Issue by lucas-varela** [starlightcms/web-templates#4]
```[tasklist]
### Tasks
- [x] Hero (2 hours, ok)
- [x] Header and Footer (2 hours, used 3 hours)
- [x] Post Card (4 hours, used 20 hours)
- [ ] Index Content
- [ ] Index Pagination
- [ ] Starlight Content
- [ ] Signup
- [ ] Post Page
- [ ] Category Page
- [ ] About Us
- [ ] Search
```
